trigger:
  - main

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-18.04'
  demands:
  - maven
  - java

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
- task: DownloadSecureFile@1
  name: 'settings_xml'
  displayName: 'Download secure file'
  inputs:
    secureFile: 'settings.xml'

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'sleyva0208'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sco-aho-msc-cuentaahorros-key'
    cliProjectName: 'sco-aho-msc-cuentaahorros'
    cliSources: '.'
    extraProperties: |
      sonar.sources=./springboot-servicio-item/src/main/java/
      sonar.java.binaries=./target
      sonar.language=java
      sonar.sourceEncoding=UTF-8

- task: Maven@3
  inputs:
    mavenPomFile: './springboot-servicio-item/pom.xml'
    goals: 'clean package -DskipTests'
    options: '--settings $(settings_xml.secureFilePath) $(MAVEN_OPTS)'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'financieraoh'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      **/*.jar
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    ArtifactName: drop
