global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: coproductos
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['coproductos:8080']