name: Maven Package

on:
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=sleyva0208
          -Dsonar.projectKey=springboot-observability-framework-key
          -Dsonar.sources=springboot-observability-frameworksrc/main
          -Dsonar.test.exclusions=springboot-observability-framework/src/test/**
          -Dsonar.tests=springboot-observability-framework/src/tests/
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: 231adeac2273382eea8475add0a49906324862d4

    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: 231adeac2273382eea8475add0a49906324862d4

    - name: Build with Maven
      run: |-
        cd springboot-observability-framework
        mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |-
        cd springboot-observability-framework
        mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
